### ISSUE TITLE
Issue converting to .JAR?

### ISSUE THREAD

**Issue by SamuelDSong** [M-AJ/WowAPI#1]
When I use the command mvn package, i get the error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.4:compile (default-compile) on project WoWAPI: Compilation failure
[ERROR] C:\Users\sam\Downloads\WowAPI-master\src\main\java\me\aj\wowapi\requests\Request.java:[3,26] error: package com.sun.deploy.util does not exist

Have i done something wrong? ._.

**Comment by M-AJ** [comment]
The dependency could be used as a package dependency and not a jar. Try adding it as a package and use "mvn clean install"
